#
# Module manifest for module 'GUIDEx'
#
# Generated by: Jonathan Dunham
#
# Generated on: 2/13/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'GUIDEx.psm1'

# Version number of this module.
ModuleVersion = '2.9.4'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'db6cf18e-9912-4a19-a508-371b5ac24600'

# Author of this module
Author = 'Jon Dunham'

# Company or vendor of this module
CompanyName = 'Jonathan Dunham'

# Copyright statement for this module
Copyright = '(c) Jonathan Dunham. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Functions for working with and converting GUIDs.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Get-UUIDFromNamespace' # Create UUID v3 or v5 from a namespace and string
    'Convert-UUIDSquished' # Converts a GUID to the format stored by Windows Installer, e.g. in the Products registry key.
    'New-WindowsTerminalUUID' # Creates a deterministic Windows Terminal profile UUID based on profile name and optional application name
    # 'Convert-UUID' # Converts a GUID to a different format, optionally reversing the first 3 groups of bytes and flipping all bit orders
    # 'Convert-UUIDBytes' # Reverses the first 3 groups of bytes in a GUID, optionally flipping all bit orders
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @(
    'Get-GUIDFromNamespace', 'gufn'
    'Convert-GUIDSquished', 'Convert-UUIDOrder', 'cvgs',
    'New-WindowsTerminalGUID', 'terminalguid'
    # 'New-GUID', 'ng'
    # 'Convert-GUID', 'cvg',
    # 'Convert-GUIDBytes', 'cvgb'
)

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{
    PSData = @{
        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('UUID', 'GUID', 'UUIDv3', 'UUIDv5', 'WindowsInstaller', 'SquishedGUID', 'SQUID', 'CompressedGUID', 'WindowsTerminal')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/TMA-2/GUIDEx/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/TMA-2/GUIDEx'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'See CHANGELOG.md'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()
    } # End of PSData hashtable
} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''
}

